Algoritmo "exercicio 1"

// Escreva um algoritmo que:
//a) Leia o nome de uma pessoa;
//b) Leia o sobrenome da pessoa;
//c) Concatene o nome com o sobrenome;
//d) Apresente o nome completo.
Var
 nome     : caractere
 sobrenome  : caractere
  completo  : caractere
  
Inicio
    escreva ("Insira seu primeiro nome aqui: ")
    leia (nome)
    
    escreva ("Insira seu(s) sobrenome(s) aqui:  ")
    leia (sobrenome)
    
    completo <- nome  +" "+  sobrenome
     escreva (completo)

Fimalgoritmo