Algoritmo "exercicio 10"
//Faça um algoritmo que leia dois números nas variáveis NumA e NumB,
//nessa ordem, e imprima em ordem inversa, isto é,
//se os dados lidos forem 5 e 9, por exemplo,
//devem ser impressos na ordem 9 e 5.

var

numA, numB : real


Inicio
    escreva ("Insira um número qualquer aqui: ")
     leia (numA)
     
     escreva ("Insira outro número: ")
     leia (numB)
     
     escreva ( "A ordem inversa dos seus números é ", numB, " e ", numA)
     
     



Fimalgoritmo